FROM nginx:alpine
COPY nginx-dashboard.conf /etc/nginx/conf.d/default.conf
# Copy views and static into nginx html folder during build
COPY ../app/views /usr/share/nginx/html/
COPY ../static /usr/share/nginx/html/static/
